### ISSUE TITLE
Support for Curve features in GML?

### ISSUE THREAD

**Issue by kusala9** [S-100ExpertTeam/khoa-s100-viewer#18]
I'm trying to get curve features working in S-127 and I can't find the right combination of GML to do it.  

this doesn't work? There are three features which allow curves in GML in S-127 but the viewer doesn't show them - I just get a message saying WARNING: failed to create feature. Is it possible to see an example of GML which the current viewer wil load?

```
    <member>
        <S-127:RouteingMeasure gml:id="FEATURE_ID_0005">
            <categoryOfRouteingMeasure>fairway system</categoryOfRouteingMeasure>
            <geometry>
                <S100:curveProperty>
                    <S100:Curve srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" gml:id="X1">
                        <gml:segments>
                            <gml:LineString>
                                <gml:posList>60.8831395 -32.4312897 61.116119 -32.524042</gml:posList>
                            </gml:LineString>
                        </gml:segments>
                    </S100:Curve>
                </S100:curveProperty>
            </geometry>
        </S-127:RouteingMeasure>
    </member>
```

**Comment by gorogara** [comment]
I just uploaded new version 1.0.11. 

It supports your data. 

Old version supports only a tag <gml:Curve>, not <S100:Curve>. 

New version supports both. 

Attached file is a sample data including your gml mentioned in this issue.

[S-127 - Curve test.zip](https://github.com/S-100ExpertTeam/khoa-s100-viewer/files/8031155/S-127.-.Curve.test.zip)
